"""Add license_plate to scooters

Revision ID: add_license_plate
Revises: 
Create Date: 2026-01-20 16:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_license_plate'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scooters', sa.Column('license_plate', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scooters', 'license_plate')
    # ### end Alembic commands ###
