"""Add qr_code to rentals table

Revision ID: add_qr_code_to_rentals
Revises: 
Create Date: 2026-01-10 18:54:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_qr_code_to_rentals'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('qr_code', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_rentals_qr_code'), 'rentals', ['qr_code'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_qr_code'), table_name='rentals')
    op.drop_column('rentals', 'qr_code')
    # ### end Alembic commands ###
