"""Make scooter_id nullable in rentals table

Revision ID: make_scooter_id_nullable
Revises: add_license_plate
Create Date: 2026-01-20 21:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'make_scooter_id_nullable'
down_revision = 'add_license_plate'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rentals', 'scooter_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rentals', 'scooter_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###
